import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__name__)))

DISCOVERY_REQUEST_BROADCAST_PORT = 7000
DISCOVERY_RESPONSE_PORT = 7001

BROADCAST_ADDRESS = "255.255.255.255"

# Gateway Config
GATEWAY_ADDRESS = None

GASS_COAP_MICROSERVICE_PORT = 5682
GASS_COAP_MICROSERVICE_PATH = "devices"
